books = [
    {
        id:1,
        title: 'Book One',
        author: 'Ebram',
        image: 'https://m.media-amazon.com/images/I/61FTxQobUKL.jpg',
        category: 'Computer',
        pages: 105,
        price: 115,
    },
    {
        id:2,
        title: 'Book Two',
        author: 'Omar',
        image: 'https://m.media-amazon.com/images/I/41N62t+ANTL._SX331_BO1,204,203,200_.jpg',
        category: 'Art',
        pages: 103,
        price: 120,
    },
    {
        id:3,
        title: 'Book Three',
        author: 'Samer',
        image: 'https://m.media-amazon.com/images/I/413pA9RcpAL._SX348_BO1,204,203,200_.jpg',
        category: 'Design',
        pages: 40,
        price: 150,
    },
    {
        id:4,
        title: 'Book Four',
        author: 'Tarek',
        image: 'https://m.media-amazon.com/images/I/415Cpbap9aL._SX331_BO1,204,203,200_.jpg',
        category: 'Computer',
        pages: 30,
        price: 200,
    },
    {
        id:5,
        title: 'Book Five',
        author: 'Mario',
        image: 'https://m.media-amazon.com/images/I/41Iiw1G0EnL._SX312_BO1,204,203,200_.jpg',
        category: 'Programming',
        pages: 160,
        price: 240,
    },
    {
        id:6,
        title: 'Book Six',
        author: 'Ismail',
        image: 'https://m.media-amazon.com/images/I/51CYOFLNoHL._SX218_BO1,204,203,200_QL40_FMwebp_.jpg',
        category: 'soft skills',
        pages: 160,
        price: 240,
    }
]